### ISSUE TITLE
Make it work on Insiders distribution

### ISSUE THREAD

**Issue by nfantone** [dotBunny/VSCode#118]
[Packaged version of the plugin](https://u3d.as/jmM) won't open project files if using the [Insiders](https://code.visualstudio.com/insiders) version of vscode.

To fix this, [the bundle identifier](https://github.com/dotBunny/VSCode/blob/2.45/Plugins/Editor/VSCode.cs#L345) should be changed to:

```cs
proc.StartInfo.Arguments = " -n -b \"com.microsoft.VSCodeInsiders\" --args " + args;
```

**Comment by reapazor** [comment]
This was resolved in 394fd11504ccba5efee5eb4fbf1c99245be227f3. 

My goal is to submit updates to the UAS once a month, i plan on doing a cleanup release end of this month. Most likely the path is going to get a nice little button to navigate to the executable etc.

**Comment by reapazor** [comment]
i'm going to leave this open as a reminder :)

**Comment by reapazor** [comment]
1e1a2e01c83a01c356dd6317b1fba2ae9771f30f improved on it

**Comment by nfantone** [comment]
@reapazor This is still not working for me after upgrading to latest plugin version (2.7) and Unity 5.4f3. Nothing happens when selecting "_Assets > Open C# Project in Code_" or clicking the "_Open_" button on the inspector for script files.

However, it _does_ work when changing the value of `UseShellExecute` to `true` [here]https://github.com/dotBunny/VSCode/blob/master/Plugins/Editor/VSCode.cs#L434).

```cs
proc.StartInfo.UseShellExecute = true;
```

Although, that raises an `InvalidOperationException` exception which is shown on Unity's console.

```cs
InvalidOperationException: UseShellExecute must be false when redirecting I/O.
System.Diagnostics.Process.Start_shell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
```

**Comment by nfantone** [comment]
I'm creating a new issue, do this doesn't go unnoticed among the closed.
